movies_list = [
    {"id": 1, "name": "Edge of Tomorrow", "score": 8.1, "genre": "Action", "language": "English", "length": 113, "release_year": 2014},
    {"id": 2, "name": "Mad Max: Fury Road", "score": 8.6, "genre": "Action", "language": "English", "length": 120, "release_year": 2015},
    {"id": 3, "name": "John Wick", "score": 7.9, "genre": "Action", "language": "English", "length": 101, "release_year": 2014},
    {"id": 4, "name": "Indiana Jones and the Last Crusade", "score": 8.2, "genre": "Adventure", "language": "English", "length": 127, "release_year": 1989},
    {"id": 5, "name": "Life of Pi", "score": 7.9, "genre": "Adventure", "language": "English", "length": 127, "release_year": 2012},
    {"id": 6, "name": "The Revenant", "score": 8.0, "genre": "Adventure", "language": "English", "length": 156, "release_year": 2015},
    {"id": 7, "name": "Toy Story", "score": 8.3, "genre": "Animation", "language": "English", "length": 81, "release_year": 1995},
    {"id": 8, "name": "Spirited Away", "score": 8.6, "genre": "Animation", "language": "Japanese", "length": 125, "release_year": 2001},
    {"id": 9, "name": "Coco", "score": 8.4, "genre": "Animation", "language": "English", "length": 105, "release_year": 2017},
    {"id": 10, "name": "A Beautiful Mind", "score": 8.2, "genre": "Biography", "language": "English", "length": 135, "release_year": 2001},
    {"id": 11, "name": "The Social Network", "score": 7.7, "genre": "Biography", "language": "English", "length": 120, "release_year": 2010},
    {"id": 12, "name": "Bohemian Rhapsody", "score": 8.0, "genre": "Biography", "language": "English", "length": 134, "release_year": 2018},
    {"id": 13, "name": "Superbad", "score": 7.6, "genre": "Comedy", "language": "English", "length": 113, "release_year": 2007},
    {"id": 14, "name": "The Hangover", "score": 7.7, "genre": "Comedy", "language": "English", "length": 100, "release_year": 2009},
    {"id": 15, "name": "Amélie", "score": 8.3, "genre": "Comedy", "language": "French", "length": 122, "release_year": 2001},
    {"id": 16, "name": "The Godfather", "score": 9.2, "genre": "Crime", "language": "English", "length": 175, "release_year": 1972},
    {"id": 17, "name": "Pulp Fiction", "score": 8.9, "genre": "Crime", "language": "English", "length": 154, "release_year": 1994},
    {"id": 18, "name": "The Departed", "score": 8.5, "genre": "Crime", "language": "English", "length": 151, "release_year": 2006},
    {"id": 19, "name": "Free Solo", "score": 8.2, "genre": "Documentary", "language": "English", "length": 100, "release_year": 2018},
    {"id": 20, "name": "Blackfish", "score": 8.1, "genre": "Documentary", "language": "English", "length": 83, "release_year": 2013},
    {"id": 21, "name": "Jiro Dreams of Sushi", "score": 7.9, "genre": "Documentary", "language": "Japanese", "length": 81, "release_year": 2011},
    {"id": 22, "name": "Forrest Gump", "score": 8.8, "genre": "Drama", "language": "English", "length": 142, "release_year": 1994},
    {"id": 23, "name": "The Shawshank Redemption", "score": 9.3, "genre": "Drama", "language": "English", "length": 142, "release_year": 1994},
    {"id": 24, "name": "Parasite", "score": 8.6, "genre": "Drama", "language": "Korean", "length": 132, "release_year": 2019},
    {"id": 25, "name": "Pan's Labyrinth", "score": 8.2, "genre": "Fantasy", "language": "Spanish", "length": 118, "release_year": 2006},
    {"id": 26, "name": "Harry Potter and the Sorcerer's Stone", "score": 7.6, "genre": "Fantasy", "language": "English", "length": 152, "release_year": 2001},
    {"id": 27, "name": "The Lord of the Rings: The Fellowship of the Ring", "score": 8.8, "genre": "Fantasy", "language": "English", "length": 178, "release_year": 2001},
    {"id": 28, "name": "Gladiator", "score": 8.5, "genre": "Historical", "language": "English", "length": 155, "release_year": 2000},
    {"id": 29, "name": "Braveheart", "score": 8.3, "genre": "Historical", "language": "English", "length": 178, "release_year": 1995},
    {"id": 30, "name": "Schindler's List", "score": 9.0, "genre": "Historical", "language": "English", "length": 195, "release_year": 1993},
    {"id": 31, "name": "Get Out", "score": 7.7, "genre": "Horror", "language": "English", "length": 104, "release_year": 2017},
    {"id": 32, "name": "The Conjuring", "score": 7.5, "genre": "Horror", "language": "English", "length": 112, "release_year": 2013},
    {"id": 33, "name": "A Tale of Two Sisters", "score": 7.1, "genre": "Horror", "language": "Korean", "length": 115, "release_year": 2003},
    {"id": 34, "name": "La La Land", "score": 8.0, "genre": "Musical", "language": "English", "length": 128, "release_year": 2016},
    {"id": 35, "name": "The Greatest Showman", "score": 7.6, "genre": "Musical", "language": "English", "length": 105, "release_year": 2017},
    {"id": 36, "name": "Les Misérables", "score": 7.5, "genre": "Musical", "language": "English", "length": 158, "release_year": 2012},
    {"id": 37, "name": "Se7en", "score": 8.6, "genre": "Mystery", "language": "English", "length": 127, "release_year": 1995},
    {"id": 38, "name": "Shutter Island", "score": 8.1, "genre": "Mystery", "language": "English", "length": 138, "release_year": 2010},
    {"id": 39, "name": "Zodiac", "score": 7.9, "genre": "Mystery", "language": "English", "length": 157, "release_year": 2007},
    {"id": 40, "name": "Titanic", "score": 7.9, "genre": "Romance", "language": "English", "length": 195, "release_year": 1997},
    {"id": 41, "name": "Pride and Prejudice", "score": 8.1, "genre": "Romance", "language": "English", "length": 129, "release_year": 2005},
    {"id": 42, "name": "The Notebook", "score": 7.8, "genre": "Romance", "language": "English", "length": 123, "release_year": 2004},
    {"id": 43, "name": "Interstellar", "score": 8.6, "genre": "Sci-Fi", "language": "English", "length": 169, "release_year": 2014},
    {"id": 44, "name": "Inception", "score": 8.8, "genre": "Sci-Fi", "language": "English", "length": 148, "release_year": 2010},
    {"id": 45, "name": "Blade Runner 2049", "score": 8.0, "genre": "Sci-Fi", "language": "English", "length": 163, "release_year": 2017},
    {"id": 46, "name": "Rocky", "score": 8.1, "genre": "Sports", "language": "English", "length": 120, "release_year": 1976},
    {"id": 47, "name": "Moneyball", "score": 7.6, "genre": "Sports", "language": "English", "length": 133, "release_year": 2011},
    {"id": 48, "name": "Rush", "score": 8.1, "genre": "Sports", "language": "English", "length": 123, "release_year": 2013},
    {"id": 49, "name": "Gone Girl", "score": 8.1, "genre": "Thriller", "language": "English", "length": 149, "release_year": 2014},
    {"id": 50, "name": "Prisoners", "score": 8.1, "genre": "Thriller", "language": "English", "length": 153, "release_year": 2013},
    {"id": 51, "name": "Oldboy", "score": 8.4, "genre": "Thriller", "language": "Korean", "length": 120, "release_year": 2003},
    {"id": 52, "name": "1917", "score": 8.3, "genre": "War", "language": "English", "length": 119, "release_year": 2019},
    {"id": 53, "name": "Saving Private Ryan", "score": 8.6, "genre": "War", "language": "English", "length": 169, "release_year": 1998},
    {"id": 54, "name": "Dunkirk", "score": 7.9, "genre": "War", "language": "English", "length": 106, "release_year": 2017},
    {"id": 55, "name": "The Good, the Bad and the Ugly", "score": 8.8, "genre": "Western", "language": "English", "length": 178, "release_year": 1966},
    {"id": 56, "name": "Unforgiven", "score": 8.2, "genre": "Western", "language": "English", "length": 131, "release_year": 1992},
    {"id": 57, "name": "Django Unchained", "score": 8.4, "genre": "Western", "language": "English", "length": 165, "release_year": 2012},
    {"id": 58, "name": "Tenet", "score": 7.3, "genre": "Sci-Fi", "language": "English", "length": 150, "release_year": 2020},
    {"id": 59, "name": "The Matrix", "score": 8.7, "genre": "Sci-Fi", "language": "English", "length": 136, "release_year": 1999},
    {"id": 60, "name": "Avatar", "score": 7.8, "genre": "Sci-Fi", "language": "English", "length": 162, "release_year": 2009},
    {"id": 61, "name": "The King's Speech", "score": 8.0, "genre": "Biography", "language": "English", "length": 118, "release_year": 2010},
    {"id": 62, "name": "Lincoln", "score": 7.4, "genre": "Biography", "language": "English", "length": 150, "release_year": 2012},
    {"id": 63, "name": "Steve Jobs", "score": 7.2, "genre": "Biography", "language": "English", "length": 122, "release_year": 2015},
    {"id": 64, "name": "Togo", "score": 8.0, "genre": "Adventure", "language": "English", "length": 113, "release_year": 2019},
    {"id": 65, "name": "Moana", "score": 7.6, "genre": "Animation", "language": "English", "length": 107, "release_year": 2016},
    {"id": 66, "name": "The Iron Giant", "score": 8.0, "genre": "Animation", "language": "English", "length": 86, "release_year": 1999},
    {"id": 67, "name": "The Intouchables", "score": 8.5, "genre": "Comedy", "language": "French", "length": 112, "release_year": 2011},
    {"id": 68, "name": "Jojo Rabbit", "score": 7.9, "genre": "Comedy", "language": "English", "length": 108, "release_year": 2019},
    {"id": 69, "name": "Borat", "score": 7.3, "genre": "Comedy", "language": "English", "length": 84, "release_year": 2006},
    {"id": 70, "name": "The Irishman", "score": 7.9, "genre": "Crime", "language": "English", "length": 209, "release_year": 2019},
    {"id": 71, "name": "The Gentlemen", "score": 7.8, "genre": "Crime", "language": "English", "length": 113, "release_year": 2019},
    {"id": 72, "name": "Heat", "score": 8.3, "genre": "Crime", "language": "English", "length": 170, "release_year": 1995},
    {"id": 73, "name": "The Rescue", "score": 8.3, "genre": "Documentary", "language": "English", "length": 114, "release_year": 2021},
    {"id": 74, "name": "The Last Dance", "score": 9.1, "genre": "Documentary", "language": "English", "length": 110, "release_year": 2020},
    {"id": 75, "name": "My Octopus Teacher", "score": 8.1, "genre": "Documentary", "language": "English", "length": 85, "release_year": 2020},
    {"id": 76, "name": "Whiplash", "score": 8.5, "genre": "Drama", "language": "English", "length": 107, "release_year": 2014},
    {"id": 77, "name": "Joker", "score": 8.5, "genre": "Drama", "language": "English", "length": 122, "release_year": 2019},
    {"id": 78, "name": "Nomadland", "score": 7.4, "genre": "Drama", "language": "English", "length": 107, "release_year": 2020},
    {"id": 79, "name": "Avatar: The Way of Water", "score": 7.6, "genre": "Fantasy", "language": "English", "length": 192, "release_year": 2022},
    {"id": 80, "name": "The Shape of Water", "score": 7.3, "genre": "Fantasy", "language": "English", "length": 123, "release_year": 2017},
    {"id": 81, "name": "Stardust", "score": 7.6, "genre": "Fantasy", "language": "English", "length": 127, "release_year": 2007},
    {"id": 82, "name": "Troy", "score": 7.2, "genre": "Historical", "language": "English", "length": 163, "release_year": 2004},
    {"id": 83, "name": "Inside Man", "score": 7.6, "genre": "Thriller", "language": "English", "length": 129, "release_year": 2006},
    {"id": 84, "name": "The Girl on the Train", "score": 6.5, "genre": "Thriller", "language": "English", "length": 112, "release_year": 2016},
    {"id": 85, "name": "Bridge of Spies", "score": 7.6, "genre": "War", "language": "English", "length": 142, "release_year": 2015},
    {"id": 86, "name": "1917", "score": 8.3, "genre": "War", "language": "English", "length": 119, "release_year": 2019},
    {"id": 87, "name": "Fury", "score": 7.6, "genre": "War", "language": "English", "length": 134, "yerelease_yearar": 2014},
    {"id": 88, "name": "The Good, the Bad and the Ugly", "score": 8.8, "genre": "Western", "language": "Italian", "length": 161, "release_year": 1966},
    {"id": 89, "name": "Django Unchained", "score": 8.4, "genre": "Western", "language": "English", "length": 165, "release_year": 2012},
    {"id": 90, "name": "True Grit", "score": 7.6, "genre": "Western", "language": "English", "length": 110, "release_year": 2010},
    {"id": 91, "name": "Zodiac", "score": 7.9, "genre": "Mystery", "language": "English", "length": 157, "release_year": 2007},
    {"id": 92, "name": "Murder on the Orient Express", "score": 6.5, "genre": "Mystery", "language": "English", "length": 114, "release_year": 2017},
    {"id": 93, "name": "The Prestige", "score": 8.5, "genre": "Mystery", "language": "English", "length": 130, "release_year": 2006},
    {"id": 94, "name": "Rocketman", "score": 7.3, "genre": "Musical", "language": "English", "length": 121, "release_year": 2019},
    {"id": 95, "name": "The Greatest Showman", "score": 7.5, "genre": "Musical", "language": "English", "length": 105, "yearrelease_year": 2017},
    {"id": 96, "name": "Pitch Perfect", "score": 7.1, "genre": "Musical", "language": "English", "length": 112, "release_year": 2012},
    {"id": 97, "name": "The Artist", "score": 7.9, "genre": "Romance", "language": "English", "length": 100, "release_year": 2011},
    {"id": 98, "name": "The Notebook", "score": 7.8, "genre": "Romance", "language": "English", "length": 123, "release_year": 2004},
    {"id": 99, "name": "La La Land", "score": 8.0, "genre": "Romance", "language": "English", "length": 128, "release_year": 2016},
    {"id": 100, "name": "Casablanca", "score": 8.5, "genre": "Romance", "language": "English", "length": 102, "release_year": 1942}
]
